#[derive(Default, Debug)]
pub enum Step {
    #[default]
    Start,
    DefineDatabaseName,
    DefineTableName,
    DefineTableOn,
    DefineTableDatabase,
    DefineTableStructure,
    DefineTableStructureOpenParen,
    DefineFieldDatatype,
    DefineFieldDatatypeOpenParen,
    DefineFieldDatatypeOption,
    DefineFieldIdentifier,
    DefineTableStructureCloseParen,
    DefineTableMode,
    DefineConstraintOpenParen,
    DefineConstraintOn,
    DefineConstraintIdentifier,
    DefineConstraint,
    DefineConstraintOptionOpenParen,
    DefineConstraintOption,
    DefineConstraintOptionCloseParen,
    DefineConstraintCloseParen,
    End,
}
